version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: solucioning_db
    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"  # Exponer para acceso externo
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    networks:
      - solucioning_network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: solucioning_backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432/employee_management
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${BACKEND_PORT:-5173}
    ports:
      - "${BACKEND_PORT:-5173}:${BACKEND_PORT:-5173}"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - solucioning_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: solucioning_frontend
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: ${API_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - solucioning_network

volumes:
  postgres_data:

networks:
  solucioning_network:
    driver: bridge 