# Versión de PRODUCCIÓN con PostgreSQL Local
# PostgreSQL instalado en el VPS (fuera de Docker)
# Aplicación en contenedores Docker

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: solucioning_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${BACKEND_PORT:-5173}
    ports:
      - "${BACKEND_PORT:-5173}:5173"
    networks:
      - solucioning_network
    env_file:
      - .env

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: solucioning_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_URL: ${API_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - solucioning_network
    env_file:
      - .env

networks:
  solucioning_network:
    driver: bridge 