# Versión de PRODUCCIÓN - docker-compose.prod.yml
# Para usar: docker-compose -f docker-compose.prod.yml up -d

services:
  # PostgreSQL Database
  # IMPORTANTE: La base de datos se llama 'employee_management', NO 'postgres'
  postgres:
    image: postgres:16
    container_name: employee_management_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: employee_management  # Nombre de la base de datos de la aplicación
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password_2025
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"  # Exponer para debugging local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres.conf:/etc/postgresql/postgresql.conf  # Configuración personalizada
    networks:
      - employee_network
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  # Backend API
  # IMPORTANTE: Se conecta a la base de datos 'employee_management'
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: employee_management_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:dev_password_2025@postgres:5432/employee_management
      SESSION_SECRET: ${SESSION_SECRET:-solucioning_session_secret_2027_ultra_secure}
      PORT: 5173
    ports:
      - "${BACKEND_PORT:-5173}:5173"
    depends_on:
      - postgres
    networks:
      - employee_network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: employee_management_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - employee_network

volumes:
  postgres_data:

networks:
  employee_network:
    driver: bridge