name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /root/solucioning-deploy
            echo "Backup antes de actualizar..."
            docker-compose exec -T db pg_dump -U postgres employee_management > backup_$(date +%Y%m%d_%H%M%S).sql
            echo "Actualizando código..."
            git pull origin main
            echo "Reiniciando contenedores..."
            docker-compose down
            docker-compose up --build -d
            echo "Verificando estado..."
            docker ps
            docker logs --tail 20 solucioning_backend 